### ISSUE TITLE
Great! But when can we expect the rest of the api?

### ISSUE THREAD

**Issue by nabbl** [malleguisse/node-jdownloader-api#1]
Especially the /downloadsv2/ endpoint would be interesting to get the current status of your downloads.

If you can provide this I will create a node-red node for this.

**Comment by malleguisse** [comment]
Yes, the downloadsv2 endpoint will be added soon, i'll try to write down incoming features at the end of the readme file.

**Comment by malleguisse** [comment]
please check the last commit !
QueryLinks will give you all links from the device and queryPackages will give you the current statuts of those links. You can give several packageUUIDS in a single call of queryPackages.
