### ISSUE TITLE
AddLinks package name

### ISSUE THREAD

**Issue by serverlesspolska** [malleguisse/node-jdownloader-api#2]
Hi, thanks for providing this awesome lib.

I have one feature request. 

Could you please add optional parametr `packageName` to the `addLinks` function? 

something like that:
```
exports.addLinks = (links, deviceId, autostart, packageName) => {
  const params = `{"priority":"DEFAULT","links":"${links}","autostart":${autostart},"packageName":"${packageName}"}`;
```

**Comment by kkm** [comment]
https://github.com/tofika/my.jdownloader.org-api-php-class/blob/master/myjdapi_class.php#L152

**Comment by MrTommy1031** [comment]
I also would like the feature so I've created PR.
https://github.com/malleguisse/node-jdownloader-api/pull/5
